//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> ErrDate { get; set; }
        public string ErrCode { get; set; }
        public string ErrMethod { get; set; }
        public string ErrDesc { get; set; }
        public string ErrInternal { get; set; }
    }
}
