//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHubPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyProfile
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string EmailId { get; set; }
        public string Description { get; set; }
        public string LogoImg { get; set; }
        public string AppType { get; set; }
        public string FolderPath { get; set; }
        public string WebSite { get; set; }
        public string AboutUs { get; set; }
        public string Vision { get; set; }
        public string Mission { get; set; }
        public int InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public string InsTerminal { get; set; }
        public Nullable<int> UpdUser { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string UpdTerminal { get; set; }
        public Nullable<decimal> AppVersion { get; set; }
    }
}
