//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHubPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnquiryList
    {
        public int Id { get; set; }
        public int RefAUId { get; set; }
        public int RefVendorId { get; set; }
        public Nullable<int> RefProdId { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string RepRemark { get; set; }
        public System.DateTime EnquiryDate { get; set; }
        public Nullable<System.DateTime> EnquiryRepDate { get; set; }
        public Nullable<System.DateTime> ReadDateTime { get; set; }
        public Nullable<int> RefCatId { get; set; }
        public Nullable<int> RefRepAUId { get; set; }
    }
}
