//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHubPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMa
    {
        public GroupMa()
        {
            this.GroupContactLists = new HashSet<GroupContactList>();
        }
    
        public int GroupId { get; set; }
        public int RefVendorId { get; set; }
        public string GroupName { get; set; }
        public int InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public string InsTerminal { get; set; }
        public Nullable<int> UpdUser { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string UpdTerminal { get; set; }
    
        public virtual ICollection<GroupContactList> GroupContactLists { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
