//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHubPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterValue
    {
        public MasterValue()
        {
            this.MenuRoleRights = new HashSet<MenuRoleRight>();
            this.ParameterMappings = new HashSet<ParameterMapping>();
            this.ParameterMappings1 = new HashSet<ParameterMapping>();
        }
    
        public int RefMasterId { get; set; }
        public Nullable<int> RefVendorId { get; set; }
        public int ID { get; set; }
        public string ValueName { get; set; }
        public string ValueDesc { get; set; }
        public Nullable<decimal> OrdNo { get; set; }
        public bool IsActive { get; set; }
        public int InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public string InsTerminal { get; set; }
        public Nullable<int> UpdUser { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string UpdTerminal { get; set; }
    
        public virtual ICollection<MenuRoleRight> MenuRoleRights { get; set; }
        public virtual MastersList MastersList { get; set; }
        public virtual ICollection<ParameterMapping> ParameterMappings { get; set; }
        public virtual ICollection<ParameterMapping> ParameterMappings1 { get; set; }
    }
}
