//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHubPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMa
    {
        public ProductMa()
        {
            this.ProductImgDets = new HashSet<ProductImgDet>();
        }
    
        public int ProdId { get; set; }
        public int RefVendorId { get; set; }
        public Nullable<int> RefCatId { get; set; }
        public string ProdCode { get; set; }
        public string ProdDescription { get; set; }
        public string RefProdCategory { get; set; }
        public string RefColor { get; set; }
        public string RefProdType { get; set; }
        public string RefSize { get; set; }
        public string RefFabric { get; set; }
        public string RefDesign { get; set; }
        public string RefBrand { get; set; }
        public string Celebrity { get; set; }
        public string ProdImgPath { get; set; }
        public Nullable<System.DateTime> ActivetillDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<decimal> WholeSalePrice { get; set; }
        public int InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public string InsTerminal { get; set; }
        public Nullable<int> UpdUser { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string UpdTerminal { get; set; }
        public string ProdName { get; set; }
        public Nullable<int> RefProdId { get; set; }
        public Nullable<int> RefStoreId { get; set; }
    
        public virtual ICollection<ProductImgDet> ProductImgDets { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
