//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHubPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public int PCId { get; set; }
        public int RefVendorId { get; set; }
        public string ProdCategoryName { get; set; }
        public string ProdCategoryDesc { get; set; }
        public Nullable<int> RefPCId { get; set; }
        public Nullable<int> Ord { get; set; }
        public string ProdCategoryImg { get; set; }
        public Nullable<int> InsUser { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
        public string InsTerminal { get; set; }
        public Nullable<int> UpdUser { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string UpdTerminal { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
